E-Shop_Online_Exam/Controllers/MarkerController.cs
using System.Security.Claims;
using EShopOnlineExam.Models;
using EShopOnlineExam.Repository.IRepository;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace EShopOnlineExam.Controllers
{
    [Authorize(Roles = "Admin, Marker, QualityControl")]
    public class MarkerController : Controller
    {
        private readonly UserManager<Candidate> _userManager;
        private readonly IUnitOfWork _unitOfWork;

        public MarkerController(UserManager<Candidate> userManager, IUnitOfWork unitOfWork)
        {
            _userManager = userManager;
            _unitOfWork = unitOfWork;
        }

        public IActionResult Index()
        {
            return View();
        }

        [Authorize(Roles = "Admin, Marker")]
        public async Task<IActionResult> GetToDoList()
        {
            var Identity = (ClaimsIdentity)User.Identity;
            var markerId = Identity.FindFirst(ClaimTypes.NameIdentifier);
            List<ToDoList> tasks = _unitOfWork.ToDoList.GetToDoListByMarkerId(markerId.Value);
            return View(tasks);
        }

        [Authorize(Roles = "Admin, Marker")]
        public async Task<IActionResult> MarkerTask(int id)
        {
            var task = (List<CandidateResults>)await _unitOfWork.CandidateResults.WhereExaminationIdFull(id);
            return View(task);
        }

        [Authorize(Roles = "Admin, Marker")]
        [HttpPost]
        public IActionResult TaskPost(List<CandidateResults> results)
        {
            foreach(var item in results)
            {
                item.candidateExamination = _unitOfWork.CandidateExamination.Get(item.candidateExamination.Id);
                item.ExamQuestion = _unitOfWork.ExamQuestion.Get(item.ExamQuestion.Id);
            }
            _unitOfWork.CandidateResults.UpdateList(results);
            _unitOfWork.Save();
            return RedirectToAction("GetToDoList");
        }


        [Authorize(Roles = "Admin, Marker")]
        public IActionResult StatusManager(int id)
        {
            var toDoList = _unitOfWork.ToDoList.Get(id);
            toDoList.Status = ToDoListStatus.Close_Request;
            _unitOfWork.ToDoList.Update(toDoList);
            _unitOfWork.Save();
            return RedirectToAction("GetToDoList");
        }
    }
}

E-Shop_Online_Exam/Views/Marker/GetToDoList.cshtml
@model IEnumerable<EShopOnlineExam.Models.ToDoList>

@{
    ViewData["Title"] = "GetToDoList";
}

<h1>Marker's task list</h1>

<table id="example" class="table table-bordered table-hover table-striped">
    <thead>
        <tr>
            <th>
                Marker Id
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Exam.Id)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.TaskDescription)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DueDate)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Status)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Marker.UserName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Exam.Id)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.TaskDescription)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.DueDate)
                </td>
                <td>
                    <button type="button" class="btn btn-success" onclick="location.href = '@Url.Action("StatusManager", "Marker", new { id = item.Id })'">
                            Request to Close
                            </button>
                </td>
                <td>
                    <a asp-action="MarkerTask" asp-route-id="@item.Exam.Id" class="btn btn-info">Do The Task</a> 
                    
                </td>
            </tr>
        }
    </tbody>
</table>


<script src="~/js/jquery-3.5.1.js" type="text/javascript"></script>
<script src="~/js/jquery.dataTables.min.js" type="text/javascript"></script>
<script src="~/js/dataTables.bootstrap5.min.js" type="text/javascript"></script>

<script>
    $(document).ready(function () {
        $.noConflict();
        var table = $('#example').DataTable();
    });</script>

E-Shop_Online_Exam/Views/Marker/MarkerTask.cshtml
@model List<EShopOnlineExam.Models.CandidateResults>

@{
    ViewData["Title"] = "MarkerTask";
}

<h1>Marker Task</h1>
<hr />
<div class="col-12 mb-3">
    <br />Candidate Question Result: result is what the candidate has assigned during the exam process.
     <br />The Marker can alter the Result of the Candidate Question.
     <br />If a Candidate Answer to Question is -1, the question wasn't answered.
     <br /> Correct = Pass | Wrong = Fail | Unmarked = Question wasn't answered


</div>
<hr />
<form class="form" asp-action="TaskPost" method="post">
    <div class="form-group">
        <input type="submit" value="Submit" class="btn btn-primary" />
    </div>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => Model.First().ExamQuestion.QuestionAnswer.TextOfQuestion)
            </th>
            <th>
                @Html.DisplayNameFor(model => Model.First().ExamQuestion.QuestionAnswer.CorrectIndex)
            </th>
            <th>
                @Html.DisplayNameFor(model => Model.First().CandidateQuestionAnswer)
            </th>
            <th>
                @Html.DisplayNameFor(model => Model.First().QuestionResult)
            </th> 
        </tr>
    </thead>
    <tbody>
        @for (int i = 0; i<Model.Count(); i++) 
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => Model[i].ExamQuestion.QuestionAnswer.TextOfQuestion)
                    <input asp-for="@Model[i].ExamQuestion.Id" hidden >
                </td>
                <td>
                    @Html.DisplayFor(modelItem => Model[i].ExamQuestion.QuestionAnswer.CorrectIndex)
                    <input asp-for="@Model[i].candidateExamination.Id" hidden>
                </td>
                <td>
                    @Html.DisplayFor(modelItem => Model[i].CandidateQuestionAnswer)
                    <input asp-for="@Model[i].CandidateQuestionAnswer" hidden>
                    <input asp-for="@Model[i].Id" hidden>
                </td>
                <td>
                    <select class="form-control" asp-for="@Model[i].QuestionResult">
                        <option value="-1">Unmarked</option>
                        <option value="1">Correct</option>
                        <option value="0">Wrong</option>
                    </select>
                </td> 
            </tr>
        }
        
    </tbody>
</table>
    <div class="form-group">
        <input type="submit" value="Submit" class="btn btn-primary" />
    </div>
</form>