E-Shop_Online_Exam/Models/ToDoList.cs
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace EShopOnlineExam.Models
{
    public enum ToDoListStatus
    {
        Invalid = -1,
        Open = 1,
        Closed = 2,
        Close_Request = 3
    }
    public partial class ToDoList
    {
        public int Id { get; set; }
        public virtual Candidate Marker { get; set; }
        public virtual CandidateExamination Exam { get; set; }
        [DisplayName("Task Description")]
        public string TaskDescription { get; set; }
        [DataType(DataType.Date)]
        [DisplayName("Due Date")]
        public DateTime? DueDate { get; set; }
        [DisplayName("Status")]
        public ToDoListStatus Status { get; set; }
    }
}

E-Shop_Online_Exam/Controllers/ToDoListController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using EShopOnlineExam.Data;
using EShopOnlineExam.Models;
using EShopOnlineExam.Repository.IRepository;

using ToDoList = EShopOnlineExam.Models.ToDoList;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Authorization;

namespace EShopOnlineExam.Controllers
{
    [Authorize(Roles = "Admin, QualityControl")]
    public class ToDoListController : Controller
    {
        private readonly UserManager<Candidate> _userManager;
        private readonly IUnitOfWork _unitOfWork;

        public ToDoListController(
            IUnitOfWork unitOfWork,
            UserManager<Candidate> userManager)
        {
            _unitOfWork = unitOfWork;
            _userManager = userManager;
        }

        public async Task<IActionResult> Index()
        {
            var cands = await _unitOfWork.ToDoList.GetAllAs();
            return View(cands);
        }

        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Create()
        {
            List<Candidate> markers = new List<Candidate>();
            var users = await _unitOfWork.Candidate.GetAllAs();
            foreach(var user in users)
            { 
                if (await _userManager.IsInRoleAsync(user, "Marker"))

                {
                    markers.Add(user); 
                }
            }
            ViewBag.Markers = markers;
            List<int> exams = new List<int>();    
            var CExams = await _unitOfWork.CandidateExamination.GetAllCandidateExaminationsAs();
            foreach (var exam in CExams) 
            {
                exams.Add(exam.Id);
            }
            ViewBag.Exams = exams;

			ToDoList toDoList = new ToDoList();
            return View(toDoList);
        }

        [Authorize(Roles = "Admin")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(ToDoList toDoList)
        {

            var marker = await _unitOfWork.Candidate.GetCandidateByEmail(toDoList.Marker.UserName);
            var exam = _unitOfWork.CandidateExamination.Get(toDoList.Exam.Id);
            ToDoList tempList = new ToDoList
            {
                Marker = marker,
                Exam = exam,
                DueDate= toDoList.DueDate,
                Status= toDoList.Status,
                TaskDescription= toDoList.TaskDescription,
            };


            _unitOfWork.ToDoList.Add(tempList);
            _unitOfWork.Save();
            return RedirectToAction(nameof(Index));
        }

        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Edit(int id)
        { 
            var toDoList = await _unitOfWork.ToDoList.GetAs(id);
            if (toDoList == null)
            {
                return NotFound();
            }
            List<Candidate> markers = new List<Candidate>();
            var users = await _unitOfWork.Candidate.GetAllAs();
            foreach (var user in users)
            {
                if (await _userManager.IsInRoleAsync(user, "Marker"))

                {
                    markers.Add(user);
                }
            }
            ViewBag.Markers = markers;
            List<int> exams = new List<int>();
            var CExams = await _unitOfWork.CandidateExamination.GetAllCandidateExaminationsAs();
            foreach (var exam in CExams)
            {
                exams.Add(exam.Id);
            }
            ViewBag.Exams = exams;
            return View(toDoList);
        }

        [Authorize(Roles = "Admin")]
        [ActionName("Edit")]
        [HttpPost]
        public async Task<IActionResult> EditSave( ToDoList toDoList)
        {


            var marker = await _unitOfWork.Candidate.GetCandidateByEmail(toDoList.Marker.UserName);
            var exam = _unitOfWork.CandidateExamination.Get(toDoList.Exam.Id);
            toDoList.Marker = marker;
            toDoList.Exam = exam;

            _unitOfWork.ToDoList.Update(toDoList);
            _unitOfWork.Save();
            return RedirectToAction("Index");
          
        }

        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> ListOfToDoList()
        {
            return View(await _unitOfWork.ToDoList.GetAllAs());
        }

        [Authorize(Roles = "Admin")]
        public IActionResult Delete(int id)
        {
            var toDoList =  _unitOfWork.ToDoList.Get(id);
            return View(toDoList);
        }

        [Authorize(Roles = "Admin")]
        [ActionName("Delete")]
        [HttpPost]
        public IActionResult DeleteOnPost(int id)
        {
            var toDoList = _unitOfWork.ToDoList.Get(id);
            _unitOfWork.ToDoList.Delete(toDoList);
            _unitOfWork.Save();
            return RedirectToAction("Index");
        }

        [Authorize(Roles = "Admin")]
        public IActionResult RequestHandler(string HandleRequest, int id)
        {
            var tempTask = _unitOfWork.ToDoList.Get(id);
            if (HandleRequest == "Accept")
            {
                tempTask.Status = ToDoListStatus.Closed;
            }
            else if (HandleRequest == "Deny")
            {
                tempTask.Status = ToDoListStatus.Open;
            }
            _unitOfWork.ToDoList.Update(tempTask);
            _unitOfWork.Save();
            return RedirectToAction("Index");
        }
    }    
}

E-Shop_Online_Exam/Views/ToDoList/Create.cshtml
@model EShopOnlineExam.Models.ToDoList

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>To Do List</h4>
<hr />
<div class="row">
    <div class="col-md-2"></div>
    <div class="col-md-8">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Marker.Id" class="control-label">Marker Information</label>
                <span asp-validation-for="Marker.Id" class="text-danger"></span>
            </div>
            <div>
                <select class="form-select" asp-for="Marker.UserName"  required
                        asp-items="@(new SelectList(ViewBag.Markers))">
                    <option disabled value="-1">Select Marker</option>
                </select>


            </div>
            <div class="form-group">
                <label class="control-label">Exam ID</label>
                    <select class="form-select" asp-for="Exam.Id" required
                            asp-items="@(new SelectList(ViewBag.Exams))">
                        <option disabled>Select Exam</option>
                    </select>

            </div>
            <div class="form-group">
                <label asp-for="TaskDescription" class="control-label"></label>
                <input asp-for="TaskDescription" class="form-control" />
                <span asp-validation-for="TaskDescription" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DueDate" class="control-label"></label>
                <input asp-for="DueDate" class="form-control" />
                <span asp-validation-for="DueDate" class="text-danger"></span>
                <input asp-for="Status" class="form-control" value="1" hidden/> 
            </div>
            <div
                <div class="container">
            <div class="form-group">
                                <br />
                <input type="submit" value="Create" class="btn btn-primary" />
                <a asp-action="Index" class="btn btn-primary">Back to List</a>
            </div>
            </div>
        </form>
    </div>
</div>


@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

E-Shop_Online_Exam/Views/ToDoList/Delete.cshtml
@model EShopOnlineExam.Models.ToDoList

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>ToDoList</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Marker)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Marker)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Exam)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Exam)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.TaskDescription)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.TaskDescription)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DueDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DueDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Status)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Status)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> 
        <a asp-action="Index" class="btn btn-primary">Back to List</a>
    </form>
</div>

E-Shop_Online_Exam/Views/ToDoList/Edit.cshtml
@model EShopOnlineExam.Models.ToDoList

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>
@*@using (Html.BeginForm("EditSave", "ToDoList")) {*@
<h4>ToDoList</h4>
<hr />
<div class="row">
    <div class="col-md-2"></div>
    <div class="col-md-8">
        <form asp-action="Edit" method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Marker.Id" class="control-label">Marker Information</label>
                <span asp-validation-for="Marker.Id" class="text-danger"></span>
            </div>
            <div>
                <select class="form-select" asp-for="Marker.UserName"
                        asp-items="@(new SelectList(ViewBag.Markers))">
                    <option>Select Marker</option>
                </select>


            </div>
            <div class="form-group">
                <label class="control-label">Exam ID</label>


                <select class="form-select" asp-for="Exam.Id"
                        asp-items="@(new SelectList(ViewBag.Exams))">
                    <option>Select Exam</option>
                </select>

            </div>
            <div class="form-group">
                <label asp-for="TaskDescription" class="control-label"></label>
                <input asp-for="TaskDescription" class="form-control" />
                <span asp-validation-for="TaskDescription" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DueDate" class="control-label"></label>
                <input asp-for="DueDate" class="form-control" />
                <span asp-validation-for="DueDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Status" class="control-label"></label>
                <select class="form-select" asp-for="Status">
                    <option>Select Status</option>
                    <option value="1">Open</option>
                    <option value="2">Closed</option>
                </select>
                <span asp-validation-for="Status" class="text-danger"></span>
            </div>
            <div class="form-group">
                <br />
                <input type="submit" value="Save" class="btn btn-primary" />
                 <a asp-action="Index" class="btn btn-primary">Back to List</a>
            </div>
        </form>
    </div>
</div>

<div>
   
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

E-Shop_Online_Exam/Views/ToDoList/Index.cshtml
@model IEnumerable<EShopOnlineExam.Models.ToDoList>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>To Do List</h1>

<p>
    <a asp-action="Create" class="btn btn-primary">Create New</a>
</p>
<table id="example" class="table table-bordered table-hover table-striped">
    <thead>
        <tr>
            <th>
              Marker Id
            </th>
            <th>
               Exam Id
            </th>
            <th>
                @Html.DisplayNameFor(model => model.TaskDescription)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DueDate)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Status)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Marker.UserName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Exam.Id)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.TaskDescription)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DueDate)
            </td>
            <td>
                @if(item.Status == ToDoListStatus.Close_Request)
                {
                    <button type="button" class="btn btn-success" name="HandleRequest" value="Accept" onclick="location.href = '@Url.Action("RequestHandler", "ToDoList", new { id = item.Id, HandleRequest = "Accept" })'">Accept</button>
                    <button type="button" class="btn btn-danger" name="HandleRequest" value="Deny" onclick="location.href = '@Url.Action("RequestHandler", "ToDoList", new { id = item.Id, HandleRequest = "Deny" })'">Deny</button>
                }
                else
                {
                    @Html.DisplayFor(modelItem => item.Status)
                }
            </td>
            <td>
                <a asp-action="Edit" class="btn btn-success" asp-route-id="@item.Id">Edit</a> 
                <a asp-action="Delete" asp-route-id="@item.Id" class="btn btn-danger">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>



<script src="~/js/jquery-3.5.1.js" type="text/javascript"></script>
<script src="~/js/jquery.dataTables.min.js" type="text/javascript"></script>
<script src="~/js/dataTables.bootstrap5.min.js" type="text/javascript"></script>

<script>
    $(document).ready(function () {
        $.noConflict();
        var table = $('#example').DataTable();
    });</script>