E-Shop_Online_Exam/Models/Exam.cs
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace EShopOnlineExam.Models
{
	public class Exam
	{
        
        [DisplayName("Exam Id")]
		public int Id { get; set; }
		public virtual Certificate Certificate { get; set; }
        public virtual List<ExamTopics>? Topic { get; set; }
        public virtual ICollection<ExamQuestion>? ExamQuestions { get; set; }
        [DisplayName("Exam Duration")]
        public int ExamDuration { get; set; }

        [DisplayName("Exam Date")]
        [DataType(DataType.Date)]
        public DateTime? ExamDate { get; set; }

    }
}

E-Shop_Online_Exam/Controllers/ExamController.cs
using EShopOnlineExam.Models;
using EShopOnlineExam.Repository;
using EShopOnlineExam.Repository.IRepository;
using EShopOnlineExam.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;

namespace EShopOnlineExam.Controllers
{
    [Authorize]
    public class ExamController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;
        private readonly UserManager<Candidate> _userManager;
        public ExamController(IUnitOfWork unitOfWork, UserManager<Candidate> userManager)
        {
            _unitOfWork = unitOfWork;
            _userManager = userManager;
        }
        //[Authorize(Roles = "Admin")]

        // Exam Id -->
        [HttpGet]
        public async Task<IActionResult> ExamUI(int id, string button)
        {
            var currentUser = await _userManager.GetUserAsync(User);
            if (User.Identity.IsAuthenticated)
            {
                ViewBag.CurrentUserName = currentUser.UserName;
            }

            ViewBag.Messages = await _unitOfWork.Messages.GetAllAs();

            var candidateExamination = await _unitOfWork.CandidateExamination.GetWithExam(id);
            var examQuestionAnswers = await _unitOfWork.ExamQuestion.WhereExamId(candidateExamination.Exam.Id);
            List<CandidateResults> candidateResults = new List<CandidateResults>();

            if(button == "Start")
            {

                foreach(var question in examQuestionAnswers)
                {
                    candidateResults.Add(new CandidateResults 
                    { 
                        ExamQuestion = question, 
                        candidateExamination = candidateExamination, 
                        CandidateQuestionAnswer = -1 
                    });
                }
                _unitOfWork.CandidateResults.AddRange(candidateResults);
                _unitOfWork.Save();
            }
            else
            {
                candidateResults = (List<CandidateResults>)await _unitOfWork.CandidateResults.WhereExaminationId(candidateExamination.Id);
            }
            return View(candidateResults);
        }


        [HttpPost]
        public async void Create(Messages model)
        {
            //Messages message = new Messages
            //{
            //	Text = model.Text,
            //	UserName= model.UserName,
            //};
            //if (message.IsValid)
            //{
            var Identity = (ClaimsIdentity)User.Identity;
            var candidateId = Identity.FindFirst(ClaimTypes.NameIdentifier);
            Candidate cand = _unitOfWork.Candidate.Get(candidateId.Value);
            model.UserName = User.Identity.Name;
            model.Sender = cand;
            model.UserId = candidateId.Value;

            //   var sender = await _userManager.GetUserAsync(candidateId.Value);
            //         model.UserId = sender.Id;
            await _unitOfWork.Messages.AddAs(model);
            _unitOfWork.Save();

            //}

        }
        [HttpPost]
        [ActionName("ExamUI")]
        public void ExamPost(string id, string examId, string timeStamp)
        {
            if (timeStamp != null)
            {
                var examination = _unitOfWork.CandidateExamination.Get(Int32.Parse(examId));
                examination.timestamp = Int32.Parse(timeStamp);
                _unitOfWork.CandidateExamination.Update(examination);
                _unitOfWork.Save();
            }
            else
            {
                string[] value = id.Split(',');
                int answer = Int32.Parse(value[0]);
                int CandidateResultsId = Int32.Parse(value[1]);
                _unitOfWork.CandidateResults.UpdateCandidateQuestionAnswer(CandidateResultsId, answer);
                _unitOfWork.Save();
            }
        }



        [HttpGet]
        public async Task<IActionResult> ExamSubmit(int Id)
        {
            ExamEngine examEngine = new ExamEngine();
            await examEngine.ExamEngineResult(_unitOfWork, Id);
            var candidateExamination = await _unitOfWork.CandidateExamination.GetWithExam(Id);
            var candidateResults = (List<CandidateResults>)await _unitOfWork.CandidateResults.WhereExaminationIdFull(candidateExamination.Id);
            var examTopics = (List<ExamTopics>)await _unitOfWork.ExamTopic.GetEnableExamTopic(candidateExamination.Exam.Id);
            ViewBag.CandidateExamination = candidateExamination;
            ViewBag.CandidateResults = candidateResults;
            ViewBag.ExamTopics = examTopics;
            return View();
        }

        [HttpGet]
        public async Task<IActionResult> ExamPDF(int Id)
        {
            var candidateExamination = await _unitOfWork.CandidateExamination.GetAllCandidateExaminationsExamId(Id);
            ExamEngine examEngine = new ExamEngine();
            var result = await examEngine.ExamEngineResult(_unitOfWork, Id);

            //return View(result);
            PdfHandler pdf = new PdfHandler(_unitOfWork);
            var constant = await pdf.GenerateCertificakePdf(Id);
            return File(constant, "application/void", "ItsPDF.pdf");
        }


    }
}

E-Shop_Online_Exam/Views/Exam/ExamSubmit.cshtml
@model EShopOnlineExam.Models.CandidateExamination

@{
    ViewData["Title"] = "ExamSubmit";
    Layout = "~/Views/Shared/_Layout.cshtml";
    double total = 0;
    double overall = 0;
    int average = 0;
}

<h1>Exam Completion</h1>


<div class="row border border-success border-2" style="margin-top:6rem">
    <div class="col-12" id="questionBody">
        <div class="tab-content">
            <div class="container">
                <div class="row mt-5">
                    <div class="tab-pane active" id="form1">
                        <form action="ExamSubmit" method="post">
                            <table class="table">
                                <thead>
                                    <tr align="center">
                                    <th>Topic Title</th>
                                        <th>Maximum Marks</th>
                                        <th>Awarded Marks</th>
                                        <th>Success Rate</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach(var examTopic in ViewBag.ExamTopics)
                                    {
                                        <tr align="center">
                                            <td>@examTopic.Topic.Title</td>
                                            <td>
                                                @examTopic.SubjectWeight
                                            </td>
                                                @{
                                                    int score = 0;
                                                    foreach (var candidateResult in ViewBag.CandidateResults)
                                                    {
                                                        if (examTopic.Id == candidateResult.ExamQuestion.ExamTopics.Id)
                                                        {
                                                            if (candidateResult.QuestionResult > 0)
                                                            {
                                                                score++;
                                                            }
                                                        }
                                                    }
                                                }
                                                <td>@score</td>
 
                                            <td>
                                                @{
                                                    average++;
                                                    total = (float)score / examTopic.SubjectWeight * 100;
                                                    total = Math.Round((total), 2, MidpointRounding.ToEven);
                                                    overall += total;
                                                }
                                                @total%
                                            </td>
                                        </tr>
                                    }
                                    
                                </tbody>
                            </table>
                        </form>
                    </div>
                </div>
                <div class="row mt-5">
                    @if(overall >= 65)
                    {
                        overall = overall / average;
                        overall = Math.Round((overall), 2, MidpointRounding.ToEven);
                        <h3 align="center">Congratulations you have passed the certificate with: <span class="h3" style="color:green">@overall</span>%</h3>
                    }else
                    {
                        <h3>You shall not pass</h3>
                    }
                </div>
                <div class="row mb-5 mt-5">
                    <hr />

                    <div class="col-10"></div>
                    <div class="col-2">
                        <button type="submit" id="submitbtn" class="btn btn-success" onclick="location.href = '@Url.Action("ExamPDF", "Exam", new { id = ViewBag.CandidateExamination.Id })'">Export To PDF</button>
                   </div>
                </div>
            </div>
        </div>
    </div>
</div>